project_name: googleanalytics_exporter
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
dockers:
  - image_templates:
      - 'docker.pkg.github.com/xplorfin/googleanalytics_exporter:{{ .Tag }}-cgo'
      - 'docker.pkg.github.com/xplorfin/googleanalytics_exporter:v{{ .Major }}.{{ .Minor }}-cgo'
      - 'docker.pkg.github.com/xplorfin/googleanalytics_exporter:latest-cgo'
    dockerfile: Dockerfile.cgo
    binaries:
      - ganalytics
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - scripts/entrypoint.sh
  - image_templates:
      - 'docker.pkg.github.com/xplorfin/googleanalytics_exporter:{{ .Tag }}'
      - 'docker.pkg.github.com/xplorfin/googleanalytics_exporter:v{{ .Major }}.{{ .Minor }}'
      - 'docker.pkg.github.com/xplorfin/googleanalytics_exporter:latest'
    dockerfile: Dockerfile
    binaries:
      - ganalytics
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=com.github.actions.name={{.ProjectName}}"
      - "--label=com.github.actions.description=Prometheus Google Annalytics Exporter"
      - "--label=com.github.actions.icon=terminal"
      - "--label=com.github.actions.color=blue"
      - "--label=repository=http://github.com/ganalytics/ganalytics"
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
brews:
  - github:
      owner: xplorfin
      name: homebrewtap-oss
    folder: Formula
    homepage:  https://github.com/xplorfin/googleanalytics_exporter
    description: Prometheus Google Analytics Exporter
    test: |
      system "#{bin}/ganalytics -v"
scoop:
  bucket:
    owner: xplorfin
    name: scoop-bucket-oss
  homepage:  https://github.com/xplorfin/googleanalytics_exporter
  description: Prometheus Google Analytics Exporter
  license: MIT
nfpms:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://ganalytics.com
    description: Prometheus Google Analytics Exporter
    maintainer: Carlos Alexandro Becker <root@carlosbecker.com>
    license: MIT
    vendor: GoReleaser
    formats:
      - deb
      - rpm
    dependencies:
      - git
# TODO: ATTENTION: Currently, the provided docker image does not support the generation of snapcraft packages. @goreleaser
#snapcrafts:
#  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
#    summary: Deliver Go binaries as fast and easily as possible
#    description: Prometheus Google Analytics Exporter
#    grade: stable
#    confinement: classic
#    publish: true